### PR TITLE
Propotype for speedup and reduce RAM usage

### PR DESCRIPTION
**Pull request by G-Francio**
Prototype to speed up fit and reduce ram usage. The main change at the moment consists in moving the fitting function to be a method of Spectrum, so that there is no need to pass the entire spectrum object to each model.

Seems to work from the first rough test, needs much more to be stable and ready for production. For sure this approach reduces the ram usage by a lot (from 60MB to 25 ish for a couple of lines, much more for more complex models)

Opening this so that anyone can work on it!

### CODE REVIEW

**Comment by G-Francio** [comment]
Caching the computation of the Gauss PSF might help as well, so that we just need to do that once instead of every time a new line is fitted

@gcupani when you have time, please check what the x is, and if it always equal to the wavelength range

**Comment by G-Francio** [comment]
I just compared the results of this fix with the ones from develop, there are indeed differences between the two, which are caused by the change in the PSF computation. I am not sure why, but until those are solved, this should be understood to not work as intended (yet)

**Comment by G-Francio** [comment]
The difference seems due to the fact that, for some unforsaken reason, the resolution changes for regions. Why, that I really don't know at the moment...

**Comment by G-Francio** [comment]
Seems to work on a spectrum and JSON provided by @Andrea, the more we check the better it is but in principle this seems to work. The way it is set up it should still allow to use psf_gauss to fit for the resolution if we want, unless we face memory issues due to the caching

**Comment by G-Francio** [comment]
The patch introduces a possible serious problem: files saved before the patch are not compatible with files created after the patch due to the lack of `psf_gauss` method of the spectrum. Unsure how to go about that...

**Comment by gcupani** [comment]
Merge into #feature/speed to continue testing and implement further improvements to decrease the computation time.

**Pull request merged**
